apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rk3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-azurefile
  resources:
    requests:
      storage: 1Gi
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: "client51"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "client51"
  template:
    metadata:
      labels:
        app: "client51"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: "client51"
          image: "chekube.azurecr.io/t5"
          ports:
          - containerPort: 80
          volumeMounts:
          - name: volume
            mountPath: "/usr/src/app"
      volumes:
          - name: volume
            persistentVolumeClaim:
              claimName: rk3      
