apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k2pc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-azurefile
  resources:
    requests:
      storage: 1Gi
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kacper"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kacper"
  template:
    metadata:
      labels:
        app: "kacper"
    spec:
      containers:
        - name: "kacper"
          image: "chekube.azurecr.io/t5"
          ports:
          - containerPort: 80
          volumeMounts:
          - name: volume
            mountPath: "/usr/src/app/public/test"
      volumes:
          - name: volume
            persistentVolumeClaim:
              claimName: k2pc      