apiVersion: v1
kind: Service
metadata:
    name: "t5-7325"
    labels:
        app: "t5-7325"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "t5-7325"